extends:
  - airbnb-base

plugins:
  - "@typescript-eslint"

env:
  es6: true
  node: true
  mocha: true

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .json
        - .ts

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeature:
    impliedStrict: true

rules:
  'import/extensions':
    - error
    - ignorePackages
    - ts: 'never'
  no-empty-function: off
  '@typescript-eslint/no-empty-function': error
  no-unused-expressions: off
  '@typescript-eslint/no-unused-expressions': error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  no-useless-constructor: off
  '@typescript-eslint/no-useless-constructor': error
  semi: off
  '@typescript-eslint/semi': error
  arrow-body-style: [error, always]
  class-methods-use-this: off
  consistent-return: off
  no-param-reassign: off
  no-plusplus: [error, { allowForLoopAfterthoughts: true }]
  no-underscore-dangle: off
  prefer-destructuring: off
  prefer-rest-params: off
  prefer-spread: off
  strict: [error, global]
  camelcase: off
  no-dupe-class-members: off
